### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by glyndavidson** [ldab/lis3dh-motion-detection#4]
Is it possible to detect in which direction an object is moving with this library?
Let's say I was only concerned with one axis: X.
Could I use this library to detect in which direction along the X axis the object was moving?
How would I go about this?

**Comment by ldab** [comment]
Yes it's possible, you can enable the interrupt on X axis only here: https://github.com/ldab/lis3dh-motion-detection/blob/165f7d5f7fc18b329e1af924937000d3ca9d52e0/examples/Basic/Basic.ino#L39

You can read the acceleration and determine the direction, as well as changing interrupt.

Closing since this is not an issue.
